### ISSUE TITLE
[#2] Mantenimiento preventivo

### ISSUE THREAD

**Issue by AgustinESI** [AgustinESI/ISOFT2-2022-ET.02#6]
Solucionar los problemas de codificación existentes en la aplicación acorde a los indicados en  la [documentación](https://agustinesi.github.io/checkstyle.html)

**Comment by Enriquesmo** [comment]
Debido a que los problemas de codificación son meramente estéticos y de formato a la hora de programar, hemos decidido que este mantenimiento ha finalizado.
